### ISSUE TITLE
NoSuchMethodError 

### ISSUE THREAD

**Issue by jadams74** [smoketurner/dropwizard-consul#38]
I'm seeing an NoSuchMethodError when trying to add console-core to my project. No clue what to think about this yet. Here's the error:

     Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHost()Ljava/lang/String;
	at com.orbitz.consul.Consul$Builder.withHostAndPort(Consul.java:382)
	at com.smoketurner.dropwizard.consul.ConsulBundle.initialize(ConsulBundle.java:105)
	at io.dropwizard.setup.Bootstrap.addBundle(Bootstrap.java:148)
	at com.helixeducation.data.enrichment.DataEnrichmentAPIApplication.initialize(DataEnrichmentAPIApplication.java:51)
	at io.dropwizard.Application.run(Application.java:74)
	at com.helixeducation.data.enrichment.DataEnrichmentAPIApplication.main(DataEnrichmentAPIApplication.java:37)

Here's the Dependencies:

        <dependency>
            <groupId>com.smoketurner</groupId>
            <artifactId>dropwizard-swagger</artifactId>
            <version>1.2.3-2</version>
        </dependency>

        <dependency>
            <groupId>com.smoketurner.dropwizard</groupId>
            <artifactId>consul-core</artifactId>
            <version>1.2.3-2</version>
        </dependency>
        <dependency>
            <groupId>com.smoketurner.dropwizard</groupId>
            <artifactId>consul-ribbon</artifactId>
            <version>1.2.3-2</version>
        </dependency>

**Comment by jadams74** [comment]
I behind on dropwizard versions.
