### ISSUE TITLE
ConsulFactory Class Member Must Be Public?

### ISSUE THREAD

**Issue by jadams74** [smoketurner/dropwizard-consul#39]
Any idea why the backing variable for the getter for ConsulFactory int the config must be public? 

I see this when private:
     io.dropwizard.configuration.ConfigurationParsingException: config.yml has an error:
  * Unrecognized field at: consul
    Did you mean?:
      - server
      - logging
      - swagger
      - metrics
      - database
        [2 more]

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:276)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:141)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:92)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:124)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:72)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:93)
	at com.helixeducation.data.enrichment.DataEnrichmentAPIApplication.main(DataEnrichmentAPIApplication.java:37)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "consul" (class com.helixeducation.data.enrichment.DataEnrichmentAPIConfiguration), not marked as ignorable (7 known properties: "ribbonClient", "server", "swagger", "database", "logging", "metrics", "oktaAuthenticator"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.helixeducation.data.enrichment.DataEnrichmentAPIConfiguration["consul"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1152)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1582)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1560)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3972)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2264)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:128)

Here's the code associated w/ the config:
    @NotNull
    @Valid
    private  ConsulFactory consul = new ConsulFactory();

    @JsonProperty
    public ConsulFactory getConsulFactory() {
        return this.consul;
    }

**Comment by jplock** [comment]
change it to `@JsonProperty("consul")` and it should work.
